---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-vs
  namespace: "{{ harbor_namespace }}"
spec:
  hosts:
  - "{{ harbor_web_harbor }}"
  gateways:
  - 
  http:
  - match:
      - uri:
          prefix: '/c/'
    route:
      - destination:
          host: harbor-harbor-core
  - match:
      - uri:
          prefix: '/api/'
    route:
      - destination:
          host: harbor-harbor-core
  - match:
      - uri:
          prefix: '/v2/'
    route:
      - destination:
          host: harbor-harbor-registry
          port:
            number: 5000
  - match:
      - uri:
          prefix: '/v1/'
    route:
      - destination:
          host: harbor-harbor-registry
          port:
            number: 5000
    fault:
      abort:
        httpStatus: 404
  - match:
      - uri:
          prefix: '/service/'
    route:
      - destination:
          host: harbor-harbor-core
  - match:
      - uri:
          prefix: '/chartrepo/'
    route:
      - destination:
          host: harbor-harbor-core
  - route:
      - destination:
          host: harbor-harbor-portal
