apiVersion: v1
kind: Secret
metadata:
  name: cloud-config-secret
  namespace: kube-system
type: Opaque
data:
  ca.crt: {{ vsphere_cp_ca | b64encode }}
  vsphere.conf: {% filter b64encode %}
[Global]
port = "{{ vsphere_port }}"
insecure-flag = "{{ vsphere_cp_csi_insecure_flag }}"
secret-name = "{{ vsphere_cp_cpi_secret }}"
secret-namespace = "kube-system"
ca-file = "/etc/cloud/ca.crt"

[VirtualCenter "{{ vsphere_cp_vcenter_address }}"]
datacenters = "{{ vsphere_datacenter }}"

[Workspace]
folder = "{{ vsphere_folder }}"
{% endfilter %}

