apiVersion: v1
kind: Secret
metadata:
  name: cpi-secret
  namespace: kube-system
type: Opaque
data:
  {{ vsphere_cp_vcenter_address }}.password: {{ vsphere_cp_password | b64encode }}
  {{ vsphere_cp_vcenter_address }}.username: {{ vsphere_cp_username | b64encode }}
