---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ vsphere_cp_csi_secret }}"
  namespace: kube-system
type: Opaque
data:
  ca.crt: {{ vsphere_cp_ca | b64encode }}
  csi-vsphere.conf: {% filter b64encode %}
[Global]
cluster-id = "{{ vsphere_cp_cluster_id }}"
ca-file = "/etc/cloud/ca.crt"

[VirtualCenter "{{ vsphere_cp_vcenter_address }}"]
port = "{{ vsphere_port }}"
insecure-flag = "{{ vsphere_cp_csi_insecure_flag }}"
datacenters = "{{ vsphere_datacenter }}"
user = "{{ vsphere_cp_username }}"
password = "{{ vsphere_cp_password }}"
ca-file = "/etc/cloud/ca.crt"

[Workspace]
folder = "{{ vsphere_folder }}"
{% endfilter %}
